### ISSUE TITLE
SQLite - Out of memory

### ISSUE THREAD

**Issue by TauanSantana** [quay/clair-action#180]
I've been trying to use this action, but without success.

- First, I download the database (almost 9gb)
- Then, I use the action to analyze.

```yaml
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v3
      - name: Run Clair V4 update
        uses: quay/clair-action@main
        with:
          db-file: clair.db
          mode: update
``` 

```yaml
    - name: Run Clair 
      uses: quay/clair-action@main
      with:
        image-ref: ${{ inputs.image }}
        db-file: clair.db 
        format: sarif
        output: clair_results.sarif
``` 

Erro:
2024/09/08 22:09:36 error creating sqlite backend: unable to open database file: out of memory (14)

Do I need to adjust anything?
I'm using a runner with 16GB of RAM
